Надо подкачаться, но не в зале
htmlacademy-javascript/1792621-keksobooking-23 pull request #10
Opened 2021-07-06 22:12 UTC by Ropot171

2021-07-07 19:16 UTC, iksah requested changes

2021-07-07 19:16 UTC, iksah commented on js/util.js
> +};
Ну или в отдельном модуле про сообщения пользователю / модалки.

2021-07-08 09:17 UTC, Ropot171 commented on js/backend.js
> +  });
У меня почему-то красным не подсвечивает( 
Как это правильно сделать? Отформатировать с помощью eslint

2021-07-08 19:26 UTC, iksah requested changes

2021-07-08 19:26 UTC, iksah commented on js/data.js
> +export {adForm};
Весь не используемый более код можно удалить. (тут и литер ругается)

2021-07-08 19:26 UTC, iksah commented on js/util.js
> +};
Я к тому, что стоит все-таки перенести :)

2021-07-08 19:26 UTC, iksah commented on js/util.js
> +      document.body.removeEventListener('keydown',errorContainer);
errorContainer - это не функция. Удалять нужно то, что было добавлено.

Нужно завести переменную под функцию - handleKeydown например.

```
const handleKeydown = () => {
  document.body.removeEventListener('keydown', handleKeydown);
}
document.body.addEventListener('keydown', handleKeydown);
```

2021-07-08 19:26 UTC, iksah commented on js/api.js
> +      changeFormState(MAP_FILTERS_CLASS);
Вот наша функция:
```
function changeFormState(isDisabled) {
   [adForm, formFilter].forEach((form) => {
     for (const element of form.elements) {
       element.disabled = isDisabled;
     }
   });
 }
```
Нет смысла передавать в неё MAP_FILTERS_CLASS, ведь disabled - булево значение.

2021-07-08 19:26 UTC, iksah commented on js/api.js
> +const POINTS_COUNT = 10;
Это свойство карты, а не api, поэтому такие данные лучше хранить в модуле карты.

2021-07-08 19:26 UTC, iksah commented on js/util.js
> +  const buttonEsc2 = 27;
1) buttonEsc - недостаточно явное название. Кажется, что это например сама кнопка, а не её код. Переименовать в key esc.
2) Не верное форматирование имен констант - KEY_ESC.
3) В предыдущей функции уже объявлены эти значения. Стоит вынести их на уровень выше.
4)  `const buttonEsc2 = 27;` - это keyCode значение для клавишы Esc. Во первых, это устаревшее и не рекомендуемое к использованию свойство. А во вторых - ты не проверяешь его в функции (`evt.key === buttonEsc2` - это про key, а не keyCode). https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

2021-07-08 19:26 UTC, iksah commented on js/api.js
> +        showSuccess();
При успешной отправке данных форма объявления должна возвращаться в дефолтное состояние.
https://up.htmlacademy.ru/javascript/23/project/keksobooking#keksobooking-2-5

2021-07-08 19:26 UTC, iksah commented on js/util.js
> +  });
Не исправлено, см коммент выше.

2021-07-11 06:58 UTC, iksah requested changes

2021-07-11 06:58 UTC, iksah commented on js/api.js
> +import {ADDRESS_POST,ADDRESS_GET} from './map.js';
Вот это лучше оставить в этом модуле, потому что с картой эти константы никак не связаны.

2021-07-11 06:58 UTC, iksah commented on js/card.js
> +const addPhotos = function (element, list){
Тоже самое - list это указание на тип :) напиши просто photos.

2021-07-11 06:58 UTC, iksah commented on js/card.js
> +const addFeatures = function (element, list) {
А здесь features

2021-07-11 06:58 UTC, iksah commented on js/userMessages.js
> +const textAlert = 'Произошла ошибка сервера, попробуйте еще раз';
1) TEXT_ALERT
2) Я бы назвал типа SERVER_ERROR_TEXT, а то вдруг какие-ещё ошибки добавим :)

2021-07-11 06:58 UTC, iksah commented on js/userMessages.js
> +  document.addEventListener('click', onDeleteMessage);
1) У нас нет события `delete message`. Здесь эту функцию стоило бы назвать просто `deleteMessage` (тем более мы используем её как обработчик разных событий)
2) **Но** такой нейминг не пройдет по дополнительным критериям академии https://up.htmlacademy.ru/javascript/23/criteries#d4

Поэтому я рекомендую сделать так:
1) Код удаления сообщения и обработчиков вынести в отдельную функцию deleteMessage
2) Сделать два отдельных обработчика для click и keydown. В обработчиках проверять isEscEvent(evt) или evt.type === 'click' соответственно и вызывать deleteMessage

2021-07-11 06:58 UTC, iksah commented on js/userMessages.js
> +  const message = document.querySelector('.displayMessage');
Этот класс выбивается из принятой в проекте нотации (здесь все по БЭМу). Давай назовем displayed-message или прост message

2021-07-11 06:58 UTC, iksah commented on js/page.js
> +adForm.addEventListener('submit', (evt) => {
Вот эти обработчики тоже должны добавляться и удаляться со страницы при активации / деактивации формы (ведь если форма не активна - то и эти обработчики никогда не должны сработать).

2021-07-12 10:16 UTC, Ropot171 commented on js/userMessages.js
> +  document.addEventListener('click', onDeleteMessage);
Я сделала только 1 пункт. 
Пока не планирую делать дополнительные критерии, хочу на базовых остановиться.) 
Если останется время\возможность- вернусь и доделаю) 
Спасибо!)

2021-07-12 12:00 UTC, iksah commented on js/api.js
> +        clearForm();
Это должно было быть внутри функции onSuccess.

2021-07-12 12:05 UTC, iksah commented on js/map.js
> +addressInput.value = `${mainMarker._latlng.lat.toFixed(5)}, ${mainMarker._latlng.lng.toFixed(5)}`;
Обращаться к приватным (если начинается с нижнего подчеркивания - считается приватным) свойствам - плохая практика. Так можно или сломать что-то, или получить не то что нужно. Давай лучше воспользуемся методом [getLatLng()](https://leafletjs.com/reference-0.7.7.html#marker-getlatlng).
Плюс лучше не вызывать два раза подряд, а вызвать один раз и сохранить в переменную (это касается метода ниже).

2021-07-12 12:07 UTC, iksah commented on js/page.js
> +  resetDataMap();
Это уже не про очистку формы получается, а про очистку всей страницы. Так что давай переименуем в clearPage / resetPage.

2021-07-12 13:22 UTC, merged