Первые функции написаны, в комментарии прописала, где брала информацию
htmlacademy-javascript/1792621-keksobooking-23 pull request #2
Opened 2021-06-02 20:45 UTC by Ropot171

2021-06-02 20:49 UTC, Ropot171 commented on js/main.js
> +  console.log('Нет интервала для вывода рандомного значения, ответ = + min');
Я не понимаю, что это за невероятная ошибка вылезла. Можете обьяснить, пожалуйста?

2021-06-03 10:18 UTC, iksah requested changes

2021-06-03 10:18 UTC, iksah commented on js/main.js
> +//Первая функция
Такой комментарий в коде - не очень информативен. Давай лучше напишем что эта функция делает (прямо как в задании - `Функция, возвращающая случайное число с плавающей точкой из переданного диапазона включительно.`). Плюс можно описать параметры и ограничения для них.  
В целом, этот комментарий можно и просто удалить, но если тебе интересно - посмотри https://jsdoc.app/about-getting-started.html. JSDoc это стандартное решение для документации апи проекта/юнита.)

2021-06-03 10:18 UTC, iksah commented on js/main.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
Давай предположим, что max = 1, а min = 2.
У нас выполнится первое условие, и в консоль будет написано о неправильном значении. При этом функция не остановится и продолжит свое выполнение.
Второе условие так-же не выполнится, а значит функция сразу-же пойдет в else блок и вернет нам значение, хотя и не должна.

Давай сделаем так:
- если функция не может вернуть значение, сделаем `console.error(...)` и вернем например `null` (или, что будет ещё лучше - кинем ошибку через `throw new RangeError(...)` ([вот здесь подробнее про эту ошибку](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError/RangeError)).
- если функция может вернуть значение, но оно не рандомное - сделаем `console.warn(...)` и вернем `min`.
- Ну а если все хорошо, ничего писать в консоль не будем, и просто вернем значение.

2021-06-03 10:18 UTC, iksah commented on js/main.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
Попробуй написать несколько кейсов для этой функции и посмотреть, что выводится в консоль, чтобы провалидировать поведение.)

2021-06-03 10:18 UTC, iksah commented on js/main.js
> +    else if (maxNumber === minNumber) {
Вот здесь такой проблемы как в прошлой функции не будет, потому что все условия написаны через if-elseif-else.)

2021-06-03 10:18 UTC, iksah commented on js/main.js
> +    else if (maxNumber === minNumber) {
Кстати, давай для читаемости напишем условия так:
```
if (cond1) {
  code1
} else if (cond2) {
  code2
} else {
  code3
}
```

иначе сложнее понять, что после конца юнита идет альтернативная ветка для условия. Потому что обычно если закрывающая фигурная скобка стоит на строчке, и за ней ничего нет - значит это конец связанного с ней кода.

2021-06-03 10:18 UTC, iksah commented on js/main.js
> +    }
Задание на звездочку.)
Эти две функции делают почти одно и тоже. Можем ли мы для получения одной из них использовать другую?

2021-06-03 10:18 UTC, iksah commented on js/main.js
> +    return Number(result.toFixed(quantity));
Есть кстати альтернативный вариант приведение к числу.)
`return +result.toFixed(quantity); `
Но здесь и твой вариант хорош.)

2021-06-03 17:43 UTC, Ropot171 commented on js/main.js
> +    return Number(result.toFixed(quantity));
Да, читала про него тоже, спасибо)

2021-06-03 19:44 UTC, Ropot171 commented on js/main.js
> +    }
Я уверена, что можно) 
Но можно я сделаю это во время рефакторинга, чуть позже? 
Надо посидеть подумать, сходу не получилось придумать, как правильно сделать)

2021-06-06 09:20 UTC, iksah requested changes

2021-06-06 09:20 UTC, iksah commented on js/main.js
> +    console.warn(min); //можно вернуть minNumber, но этим мы можем запутать пользователя
Если мы ничего не возвращаем, нужно тогда явно уведомить пользователя функции.
Например, можем кидать ошибку как и выше (или просто объединить эти кейсы).

2021-06-06 09:20 UTC, iksah commented on js/main.js
> +}
Смотри, у нашего пулу-реквеста есть несколько проблем с ESLint проверкой.
1) Функции не используются, давай добавим в конце файла по одному вызову написанных нами функций.
2) Я совсем забыл, что у нас линтер не пропускает логгирование в консоль, придется заменить строки с console.
3) Местами в конце строк у нас пробелы, что тоже не поощрается литером.
4) В первом комментарии немного не соотносятся пробелы. Плюс, давай будем оставлять пробел после тегов открытия/закрытия комментария `/*_comment_*/`

2021-06-07 17:45 UTC, merged