Первичная сдача задания
htmlacademy-javascript/1792621-keksobooking-23 pull request #3
Opened 2021-06-07 19:54 UTC by Ropot171

Все смогла сделать, кроме двух значений: 

```
1. avatar
2. address:
```

2021-06-08 21:42 UTC, iksah requested changes

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +const arrPhotos =['https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/duonguyen-8LrGtIxxa4w.jpg', 'https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/bra
Обычно в проектах выбирается определенная длина строки, и при разработке если код вылезает за заданные рамки - его переносят на новую строку. Обычно за такое ограничение берут 80 или 120 символов.
Давай отформатируем код соответствующим образом.)
Будет что-то в духе:
```
const arr = [
  1,
  2
]
```
Заодно в списках, если они оформлены таким образом, часто ставят trailing comma - запятую после последнего элемента. С одной стороны большинство форматтеров автоматически выровняют код нужным образом, а с другой стороны - так будет проще добавлять новые элементы.) Будет что-то в таком духе:

```
const arr = [
  1,
  2, // вот здесь запятая.
]
```

Так же, там потерялся пробел после знака =.
И напоследок - в названиях переменных обычно не отображает тип этой переменной. Что касается писков - слова во множественном числе более чем достаточно. А значит должно быть просто `photos`.

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +function GenerateObjects() {
В данном случае у нас обычная функция, а не класс/конструктор/перечисление, а значит название должно быть написано с маленькой буквы.

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +function getRandomTime () {
Давай после каждого юнита кода оставлять одну пустую строку, чтобы было проще читать:
```
function getRandomPlace() {
}
// вот здесь пустая строка
function getRandomTime () {
}
```

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +  return arr[index];
1) Давай переименуем arr в types или в placeTypes.
2) Давай сделаем отдельную функцию, которая будет возвращать случайный элемент списка
```
получить_случайный_элемент(список)
```

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +        avatar: /*/img/avatars/user*/`0${getRandomNumber(1,8)}`,/*.png*/
```
avatar: `/img/avatars/user0${getRandomNumber(1,8)}.png`
```

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +          }*/
У объекта есть свойство `location`. Здесь нам нужно записать данные этого свойства, но в формате одной строки. Для этого нужно как то получить эти значение **до** создания объекта и обратиться здесь к ним.

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +        features: 'wifi, dishwasher, parking, washer, elevator, conditioner',
Здесь должен быть массив строк, а не одна строка. Кроме того, это должно быть массив случайной длинны из случайных значений.

2021-06-08 21:42 UTC, iksah commented on js/main.js
> +        photos: arrPhotos.join(', '),
Так же как и с `features`. Это должен быть массив строк, а не строка. Кроме того здесь должны быть несколько случайных элементов из списка `arrPhotos`.

2021-06-10 18:05 UTC, Ropot171 commented on js/main.js
> +    }
Я совсем не понимаю, как сделать так, чтобы значения не повторялись, подскажи, пожалуйста

2021-06-10 18:05 UTC, Ropot171 commented on js/main.js
> +const arrPhotos =['https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/duonguyen-8LrGtIxxa4w.jpg', 'https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/bra
Сделала

2021-06-10 18:06 UTC, Ropot171 commented on js/main.js
> +function GenerateObjects() {
Исправила

2021-06-10 18:06 UTC, Ropot171 commented on js/main.js
> +function getRandomTime () {
Исправила

2021-06-10 18:06 UTC, Ropot171 commented on js/main.js
> +  return arr[index];
Исправила и написала функцию)

2021-06-10 18:06 UTC, Ropot171 commented on js/main.js
> +        avatar: /*/img/avatars/user*/`0${getRandomNumber(1,8)}`,/*.png*/
Исправила, спасибо

2021-06-10 18:06 UTC, Ropot171 commented on js/main.js
> +          }*/
Исправила)

2021-06-10 18:07 UTC, Ropot171 commented on js/main.js
> +        features: 'wifi, dishwasher, parking, washer, elevator, conditioner',
Я сделала случайной длины, но как сделать так, чтобы значения не повторялись - не могу понять(

2021-06-10 19:49 UTC, Ropot171 commented on js/main.js
> +        features: 'wifi, dishwasher, parking, washer, elevator, conditioner',
Кажется, что мой код решает эту задачу, если я правильно ее поняла, сложно)

2021-06-10 21:40 UTC, iksah requested changes

2021-06-10 21:40 UTC, iksah commented on js/main.js
> +  return list[Math.floor((Math.random()*list.length))];
Давай используем здесь написанную нами функцию получения случайного числа.)

2021-06-10 21:40 UTC, iksah commented on js/main.js
> +  return arr[index];
А здесь функцию получения случайного элемента списка.

2021-06-10 21:40 UTC, iksah commented on js/main.js
> +function getRandomLine(line) {
Здесь мы получаем не случайно линию, а случайный подсписок списка. Или случайные элементы списка. Давай назовём соответствующе - например getRandomElement**s**.

2021-06-10 21:40 UTC, iksah commented on js/main.js
> +function getRandomLine(line) {
И line это список - array / list / elements.

2021-06-10 21:40 UTC, iksah commented on js/main.js
> +  }
Пусть будет так, но хочу подсветить проблемы текущего решения:
1) Если в оригинальном списке будут повторяющиеся элементы, в результирующий не смогут попасть оба  элемента - только один экземпляр.
2) Если lengthOfArray будет близка maxLength (например 99 и 100), то такая функция может работать оооооооооооочень долго.  Потому что когда она выбрет 98 элементов, то останется только 2 элемента из оригинального списка, которых нет в списке случайных элементов. Их поиск займет немало времени.

Лучшим решением было бы скопировать оригинальный список и вырезать оттуда по одному элементу, пока не заполним список случайных элементов нужным количеством.

2021-06-10 21:40 UTC, iksah commented on js/main.js
> +      location: location,
Получается что у всех 10 элементов будут одинаковые location и address ?

2021-06-10 21:40 UTC, iksah commented on js/main.js
> +    const objects = {
Здесь должно быть единственное число.

2021-06-12 21:59 UTC, merged