Первая итерация
htmlacademy-javascript/1792621-keksobooking-23 pull request #5
Opened 2021-06-17 20:16 UTC by Ropot171

2021-06-19 07:36 UTC, iksah requested changes

2021-06-19 07:36 UTC, iksah commented on js/popup.js
> +)};
1) Давай оформим это в виде функции рендеринга одного объявления, которую мы экспортируем и используем в main.js
2) У нас нет similarWizards ;) данные мы должны сгенерировать с помощью написанной ранее функции generateObjects
3) Отренедрить нужно только одно объявление, а не все
4) Подумай, как скрывать чата объявления, если данных нет - например нет описания или адреса
5) Обязательно посмотри шаблон - это пример того, что должно получиться. (он ведь уже есть в index.html https://github.com/htmlacademy-javascript/1792621-keksobooking-23/blob/master/index.html) :)

2021-06-19 07:36 UTC, iksah commented on js/popup.js
> +popElement.querySelector('.popup__text--price').textContent = offer.price + '₽/ночь';
Давай лучше воспользуемся интерполяцией, чтобы везде все выглядело одинаково:
``` `${offer.price} ₽/ночь` ```

2021-06-19 07:36 UTC, iksah commented on js/popup.js
> +popElement.querySelector('.popup__type').textContent = offer.type;
Здесь нам нужно выбрать подходящее значение под тип жилья:

> В блок .popup__type выведите тип жилья offer.type, сопоставив с подписями:
> - Квартира для flat
> - Бунгало для bungalow
> - Дом для house
> - Дворец для palace
> - Отель для hotel

Это можно сделать или с помощью обычного перечисления, или с помощью switch-case конструкции.

2021-06-19 07:36 UTC, iksah commented on js/popup.js
> +popElement.querySelector('.popup__text--capacity').textContent = `${offer.rooms} комнаты для ${offer.guests} гостей`;
Здесь нужно подумать про правильные окончания для комнат и гостей. Ведь может быть и `1 комната для 1 гостя`.
Для этого нужно написать функции, которые по данному числу будут отдавать правильные варианты слов.

2021-06-19 07:36 UTC, iksah commented on js/popup.js
> +popElement.querySelectorAll('.popup__features');
Внутри этого блока уже есть элементы (посмотри в шаблоне). Тебе нужно скрыть те, которых нет в данном объявлении.

2021-06-19 07:36 UTC, iksah commented on js/popup.js
> +popElement.querySelector('.popup__photos').picture.src = offer.photos;
Здесь нужно наполнить список фотографиями, ведь фотографий может быть много (photos - это список).
Для каждой фотографии нужно создать отдельный img на основе того, что есть внутри `.popup__photos`

2021-06-19 20:14 UTC, Ropot171 commented on js/popup.js
> +)};
1. Подскажи, пожалуйста, как отгенерить только одно обьявление 
2. Совсем нет идей, как сделать правильно п.5. Возможно, надо добавить класс и через if потом проверить значения.... Не очень пока понимаю, можно еще подсказку, пожалуйста?)

2021-06-20 18:22 UTC, iksah requested changes

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +      photo.style = 'height:' + '70px';
1) нет смысла разбивать на несколько частей  'height:' + '70px'; - можно просто  'height: 70px';
2) код на строчке 10 переопределяет свойство на строке 9. Ширина задана нее будет.
3) Лучше взять и скопировать img элементов шаблона.

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +var ApartmentType = {
Почему var, а не const ?

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +    plaseListElement = document.querySelector('.popup__features');
А где объявляется эта переменная? И название не соответствует содержимому (plaseList - это не фичи)

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +      const modifer = item.classList[1];
Не очевидно, почему здесь 1. А что, если в шаблоне классы будут в другом порядке?

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +var room = offer.rooms;
отступы потерялись.

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +}
Функция ничего не возвращает, а только выводит в консоль.

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +};
1) Здесь смешано несколько разных действий. Если так делать - нужно внутри выделять логические блоки и выносить из в отдельные функции. Рендер карточки нужно вынести отдельно
2) Функция называется getCard, но совершает много других действий, а значит не соответствует названию.

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +  };
Не должно быть записи данных в window. Все что используется в других модулях должно быть экспортировано.

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +popElement.querySelector('.popup__avatar').src = data.author.avatar;
Сделай пожалуйста функцию `renderCard(card)`. В этой ситуации `card` - это первый из сгенерированных `generateObjects` объектов. Данная функция не должна ничего возвращать.
Давай сделаем по заданию, и обрисуем его в `#map-canvas`.

> Отрисуйте один из сгенерированных DOM-элементов, например первый, в блок #map-canvas, чтобы проверить, что данные в разметку были вставлены корректно.

2021-06-20 18:22 UTC, iksah commented on js/popup.js
> +    var card = document.querySelector('template').content.querySelector('.map__card');
А что, если будет другой темплейт перед этим? Можно получить нужный темплейт по id.
```
<template id="card">...</template>
```

2021-06-20 18:24 UTC, iksah commented on js/popup.js
> +)};
1) Вот два комментария по этому поводу:
https://github.com/htmlacademy-javascript/1792621-keksobooking-23/pull/5#discussion_r654968268
https://github.com/htmlacademy-javascript/1792621-keksobooking-23/pull/5#discussion_r654970946

2021-06-23 11:46 UTC, iksah requested changes

2021-06-23 11:46 UTC, iksah commented on js/renderMap.js
> +  for (let i = 0; i < card.length; i++) {
Выполни в проекте пожалуйста команду `npm i eslint-config-htmlacademy@latest -DE` - тут обновление конфета, чтобы eslint не ругался на `i`.

2021-06-23 11:46 UTC, iksah commented on js/data.js
> +export default generateObjects;
Я бы вернул named export (`export {generateObjects}`). Это проще расширять (если будут другие экспортируемые функции, а дефолтный экспорт может быть только один.), плюс будет консистентно с другими модулями.

2021-06-23 12:02 UTC, iksah requested changes

2021-06-23 12:02 UTC, iksah commented on js/data.js
> +import {renderCard} from'./renderMap.js';
Модуль лучше назвать `card.js`

2021-06-23 12:10 UTC, iksah commented on js/renderMap.js
> +  }
Ну и вообще, если делать совсем правильно - нужно не по значению смотреть, а по последней цифре.
`21 комната для 21 гостя` например.
У нас значения ограничены (1, 2, 3 и 100 комнат), так что можно прямо по ним сделать

> 1 комната — «для 1 гостя»;
> 2 комнаты — «для 2 гостей» или «для 1 гостя»;
> 3 комнаты — «для 3 гостей», «для 2 гостей» или «для 1 гостя»;
> 100 комнат — «не для гостей».

2021-06-23 12:11 UTC, iksah commented on js/renderMap.js
> +  cardElement.querySelector('.popup__features').appendChild(getFeatures(card.offer.features));
Или если фич не будет?

2021-06-23 12:17 UTC, iksah commented on js/renderMap.js
> +}
Вот тут подсветил несколько проблем, о которых написано в других комментариях
![Uploading Screenshot 2021-06-23 at 3.14.59 PM.png…]()

2021-06-23 18:48 UTC, Ropot171 commented on js/renderMap.js
> +  }
Я это реализую в рамках рефакторинга чуть позже :) Если можно конечно)

2021-06-23 18:54 UTC, Ropot171 commented on js/renderMap.js
> +  }
:peka_namekaet 
:pepe_please

2021-06-23 18:58 UTC, Ropot171 commented on js/renderMap.js
> +  let result = null;
Так не работает, возникает ошибка и не запускается проект :(

2021-06-24 17:44 UTC, iksah commented on js/card.js
> +  });
1) Нужно сделать через фрагмент.
https://up.htmlacademy.ru/javascript/23/criteries#b25
2) Если функция ничего не возвращает - это не get. Здесь можно назвать renderPhotos / addPhotos / appendPhotos например.

2021-06-24 17:44 UTC, iksah commented on js/card.js
> +  }
Лучше пойти от обратного - идти по элементам, которые уже в DOM, и если у них нет нужного класса - удалять их. Ведь не просто так они уже добавлены в разметку. Что если в разметку внесут ещё какие-то изменения?

И тоже нейминг.

2021-06-24 17:44 UTC, iksah commented on js/card.js
> +function generateRoomText({offer}) {
Лишняя деструктуризация. ЛУчше просто `generateRoomText(offer)`

2021-06-24 17:44 UTC, iksah commented on js/card.js
> +  let result = null;
Просто `let result;`

2021-06-24 17:44 UTC, iksah commented on js/card.js
> +
Можно вообще не вводить переменную, а возвращать сразу в if. Так будет проще читаться, ведь сразу ясно, что больше ничего делаться не будет.

2021-06-24 17:46 UTC, merged