Module7 task2
htmlacademy-javascript/1792621-keksobooking-23 pull request #8
Opened 2021-06-26 10:05 UTC by Ropot171

Первая попытка

2021-06-29 20:25 UTC, iksah requested changes

2021-06-29 20:25 UTC, iksah commented on index.html
> +>>>>>>> master
Вот здесь конфликт от мержа веток.
```
<<<<<<< HEAD
   <script type="module" src="js/validate.js"></script>
   <script type="module" src="js/activatePages.js"></script>
 =======
   <script type="module" src="js/validate.js"></script>
 >>>>>>> master
```
 Нужно оставить один из двух вариантов, или поправить на свой третий.)

2021-06-29 20:25 UTC, iksah commented on js/activatePages.js
> +const DisabledOnFormNodes = (isDisabled) => {
1) Почему с большой буквы?
2) Это функция, но нет глагола в названии.

2021-06-29 20:25 UTC, iksah commented on index.html
> +            <option value="14:00"disabled>Выезд до 14</option>
Зачем здесь disabled?

2021-06-29 20:25 UTC, iksah commented on js/activatePages.js
> +  DisabledOnFormNodes(bool);
1) Проблемы с именованием как в функции выше.
2) bool никак не характеризует переменную. Название должно отражать назначение переменной, а не её тип.

2021-06-29 20:25 UTC, iksah commented on index.html
> +>>>>>>> master
Вообще здесь нужно подключить только main.js. Остальные модули используются main.js и дополнительно импортировать их не нужно.

2021-06-29 20:31 UTC, iksah commented on js/main.js
> +PageActiveState(false);
Сейчас при открытии страницы она в активном состоянии. Что-то не так с логикой работы функции.

2021-06-30 18:47 UTC, Ropot171 commented on js/main.js
> +PageActiveState(false);
Я не могу понять, как сделать правильно(

2021-06-30 18:47 UTC, Ropot171 commented on js/main.js
> +PageActiveState(false);
Можно подсказку, пожалуйста?

2021-07-02 08:31 UTC, iksah commented on js/activatePages.js
> +const noActivateThePage = (state) => {
Давай все же ещё раз переименуем.)
1) noActivate => deactivate
2) артикли обычно в названиях функций не пишутся, так что просто deactivatePage
3) Если в названии функции явно указано, что будет деактивация - будет странным активировать что-либо. Поэтому лучше changePageState(isActive)
4) Кажется в других файлах функции объявляли не через стрелки, а через `function name() {...}`. Давай для единообразия и здесь так сделаем.
5) Поскольку с одной стороны страница у нас одна, а функций работы с ней может добавиться, давай переименуем варил в `page.js`.

2021-07-02 11:22 UTC, merged